name: API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -R   # ✅ optional debug

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list  # confirm 'requests' and others installed
          pip list  # ✅ confirm 'requests' installed

      - name: Run pytest
        run: |
          pytest hybrid-framework/tests --maxfail=1 --disable-warnings -q
